<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PQDUMFKF" failures="1" tests="8" name="Test Get, Post, Put, Patch, Delete and Validate" time="5.489" errors="0" timestamp="2025-03-07T13:13:24 ICT">
  <testcase classname="api.auto.test.CreateUserTest" name="testPostCreateUsers" time="1.772"/>
  <testcase classname="api.auto.test.GetUserTest" name="testGetListUsers" time="0.123"/>
  <testcase classname="api.auto.test.UpdateUserTest" name="testPatchUser" time="0.566"/>
  <testcase classname="api.auto.test.DeleteUserTest" name="testDeleteUser" time="0.443"/>
  <testcase classname="api.auto.test.NegativeTest" name="testInvalidInput" time="0.727"/>
  <testcase classname="api.auto.test.EdgeCaseTest" name="testMaximumBoundary" time="0.614"/>
  <testcase classname="api.auto.test.EdgeCaseTest" name="testMinimumBoundary" time="0.458"/>
  <testcase classname="api.auto.test.EdgeCaseTest" name="testOutOfRange" time="0.455">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;400&amp;gt; but was &amp;lt;201&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <201>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at api.auto.test.EdgeCaseTest.testOutOfRange(EdgeCaseTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at api.auto.test.TestRunner.main(TestRunner.java:10)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testOutOfRange -->
</testsuite> <!-- Test Get, Post, Put, Patch, Delete and Validate -->
